### ISSUE TITLE
setBlocks（2点で指定される直方体をブロックで埋める）が動かない時がある

### ISSUE THREAD

**Issue by Naohiro2g** [takecx/RemoteControllerMod#18]
API：setBlocks(x0, y0, z0, x1, y1, z1, dummy, dummy, blockID)
Scratch3：[ (　) ブロックを ( (　), (　), (　) ) から ( (　), (　), (　) ) まで置く]

このAPIは、空間中の2点のxyz 座標を指定し、それによって決まる直方体を指定ブロックで埋めるものだが、直方体だけでなく、平面、直線、点を描くことも想定されている。しかし、x,y,zいずれかの座標指定が(0, 0, 0, 0, 2, 0)などのように開始点＝終了点のものを含んでいるとき、ブロックが置かれない。

**Comment by takecx** [comment]
@Naohiro2g 
私の方で確認したところ、頂いたプルリクの内容で想定通りの動作ができていました。
modのver. 1.16.5_0.05 をリリースしたので確認いただき問題なければcloseしようかと思います。

**Comment by Naohiro2g** [comment]
（ダミー）パラメーター削除含め、PytonとScratch3で確認しました！

**Comment by takecx** [comment]
問題無さそうなのでcloseします
