### ISSUE TITLE
modファイルのビルド時に「SpawnEntityMessageToClient というクラスが見つからない」エラー

### ISSUE THREAD

**Issue by Naohiro2g** [takecx/RemoteControllerMod#20]
手元でRemoteControllerModをビルドして、modファイルをマイクラにインストールする環境が構築できたが、実はエラーメッセージが出ていた。SpawnEntityMessageToClient というクラスが見つからないというもの。

参照している部分をコメントアウトして無理やりビルドを通しているが、宣言が足りないか、あるいは、環境構築の手順に誤りがあるのかも。

（ちなみに、Minecraft, ForgeのバージョンとGradleのバージョンが適合していないのでは？という疑問もある。）

#### Java JDK8をインストール 
 - インストーラー Java SE Development Kit 8u291を実行
#### Gradle 4.10.3をインストール
 - gradle-4.10.3フォルダをProgram Filesフォルダにコピー
#### Forge Mdkをインストール
 - インストーラー Minecraft Forge - MC 1.16.5-36.1.0実行
#### システム環境変数PATHを編集
 - C:\Program Files\gradle-4.10.3\binを追加
 - （C:\Program Files (x86)\Common Files\Oracle\Java\javapathを追加？）

#### ビルド
 - gradle build
 - 場合によっては、最初にgradle cleanが必要？
#### modファイルの入れ替え
 - 成果物は、build/reobfjar/output.jar
 - インストール先は、ユーザーフォルダ/Appdata/Roaming/.minecraft/mods/
 - ファイル名はそのままでも問題なし。おそらくビルドタスクで規定できるのでは？？

**Comment by takecx** [comment]
@Naohiro2g 
issueありがとうございます！
ちょっとまだ確認出来てないんですが、ローカルで開発してた別の機能の内容が誤ってcommitされている可能性があります🙇‍♂️
確認でき次第またコメントさせてもらいます！

**Comment by Naohiro2g** [comment]
はーい、特に急がないです。使ってない部分なんですかね。

あわせて環境構築などもドキュメント化していきませんか？　協力者を増やしましょう。

**Comment by takecx** [comment]
@Naohiro2g 
> あわせて環境構築などもドキュメント化していきませんか？　協力者を増やしましょう。

まずは私の方でまとめてみます！
協力してくれる方が増えたら嬉しいですね！😂

**Comment by takecx** [comment]
#21 で解決したのでcloseします

**Comment by takecx** [comment]
#23 にドキュメント作成用のissueを作成しました
