### ISSUE TITLE
動いたり動かなくなったりする？

### ISSUE THREAD

**Issue by selfee-jp** [takecx/RemoteControllerMod#9]
最初、動かなかったのですが再起動で動くようになりました。
動きが不安定なので質問も含めて相談させてください。

・chrome
・Windows10
・Minecraf 1.16.5

起動する順序ってあるのでしょうか。起動時に連携したりしなかったりします。
Scratchで操作していて、時々連携しなくなりScratchとMinecrafを再起動させます。

連携しているかの確認にはX座標がとれるか、天候をかえられるかをScratchで
やってみています。

**Comment by takecx** [comment]
@selfee-jp 
> 起動する順序ってあるのでしょうか。起動時に連携したりしなかったりします。
Scratchで操作していて、時々連携しなくなりScratchとMinecrafを再起動させます。

起動順は関係無いようなコードを入れているつもりなのですが、もしかしたら不具合があるかもしれません。
一度調査したいと思いますが、以下の順序で起動していただくとおそらく確実に動作するかと思われます。
- Windows 10
- Minecraft 1.16.5
  - ワールドを選択してワールドを起動するところまで行ってください
- chrome
  - [1.16.5用のScratch](https://takecx.github.io/scratch-gui/1-16-5/)にアクセスして、Minecraft用の拡張機能を選択したタイミングで、modとの通信が確立されます

上記手順でも動作しない場合はご連絡ください 🙇

**Comment by takecx** [comment]
@selfee-jp 
> 起動順は関係無いようなコードを入れているつもりなのですが、もしかしたら不具合があるかもしれません。

確認したところ、やはりバグがありました 🙇 
#10 に詳細は記載していますが、とりあえず修正を行いましたのでこれで起動順序は関係なくなるかと思います。（ #10 とは別に #11 の問題が発覚したのでそちらは未解決です）

**Comment by takecx** [comment]
@selfee-jp 
#11 の問題にも対応いたしました。
これでワールドに何度も入るようなことをしても正常に通信できると思います。

#10 と #11 に対応したmodのバージョンが以下から入手可能となっておりますので、お試しください。
https://www.curseforge.com/minecraft/mc-mods/remote-controller/files/3357426

**Comment by takecx** [comment]
@selfee-jp 
確認いただいて、もし問題が内容であればここにコメントいただけると幸いです。
問題が無いことが確認でき次第、本issueはcloseしたいと思います 🙇

**Comment by selfee-jp** [comment]
問題は解決されたようです。
ありがとうございます。

**Comment by takecx** [comment]
問題解決したようなのでcloseします
